### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.LicenseHeaderUpdater#1]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

As with your ArgumentBinder addin I wanted to ask if it would be possible to add the `cake-contrib` user on NuGet as a co-owner to increase the visibility of the addin and also to ensure its long term maintainability?

Also if you're interested in moving the code to the [cake-contrib](https://cakebuild.net/community/cake-contrib) organization let me know. 

If you have any questions about this, please let me know.

Thanks!

**Comment by xforever1313** [comment]
I added cake-contrib as a use on NuGet.  I'll be happy to move it to the cake-contrib organization on GitHub, I just need to be reminded on how to do that :P

**Comment by pascalberger** [comment]
@xforever1313 Thanks! I approved the request. 

You can transfer the repo to me and I'll then transfer it into the cake-contrib organization and setup everything.

**Comment by xforever1313** [comment]
I put in the transfer request.  Thanks!

**Comment by pascalberger** [comment]
@xforever1313 Thanks 👍 Repo has been transfered. I also created an AppVeyor project for it with Coveralls token defined. At them moment you don't have access to AppVeyor settings, this should also work tomorrow.

Let me know if you have any questions or need some help.

**Comment by xforever1313** [comment]
:tada: :tada: :tada:
